spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  secret: MySuperSecretKeyForJwtAuth1234567890
  expiration: 3600000