spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/orders
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

grpc:
  client:
    product-service:
      address: "static://localhost:9090"
      negotiationType: plaintext
