spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/products
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
grpc:
  server:
    port: 9090